---
title: "COVID-19 and Residential Property Crime in Chicago, IL"
description: |
  My econometics project seeking to understand the impact of the COVID-19 pandemic on residential property crime in Chicago's 77 community areas.  
author:
  - name: Erin Franke
    url: {}
date: 12-15-2021
preview: chicago.png
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

In Fall 2021 I took Econometrics (ECON 381) at Macalester College. With the COVID-19 pandemic still looming and consistently and feeling like doing a project related to my hometown, I decided to learn more about COVID-19 and residential property crime on the neighborhood level. Over the course of my analysis (March 2019 - Feb 2021), I found one neighborhood to have a significant increase in residential property crime (Lincoln Square) and 15 neighborhoods to have a significant decrease in residential property crime. Overall, I found significant evidence that property crime decreased for Chicago as a whole with the onset of the pandemic. My statistical methods included fixed and random effects modeling as well as Granger causality. Please check out [my paper](finalMetricsPaper.pdf) to learn more!